version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRS_DB=netflix
      - POSRGRES_HOST=db
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=netflix
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data