version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSRGRES_HOST=db
      - POSTGRS_DB=postgres
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=netflix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data