name: Netflix

on: [push]

jobs:
  run-tests:
    services:
      postgres:
        images: postgres:11
        env:
          POSTGRES_DB=netflix
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=123
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@2
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest