name: Second Server Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # - uses: actions/checkout@v1
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: 172.104.143.233
        USERNAME: root
        PASSWORD: jobir2000JOBIR
        PORT: 22
        #SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
        #KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ~
          cd netflix
          git pull https://github.com/UmirovJobir/netflix.git
          docker-compose down
          docker-compose build
          docker-compose up
      
      
